[build]
  command = ""
  # If you're not building any front end here, set publish to "" or remove it.
  # If you have a front end on Netlify, set it to your build folder. e.g. "dist"

[functions]
  directory = "netlify/functions"
